name: Stable Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: release-master
  cancel-in-progress: false

jobs:
  release:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore: release')"
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: git fetch --tags

      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}