name: Release Candidate

on:
  push:
    branches:
      - next

concurrency:
  group: release-next
  cancel-in-progress: false

jobs:
  release:
    uses: ./.github/workflows/release-reusable.yml
    with:
      preRelease: rc
    permissions:
      contents: write